/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // National AYUSH palette — every component reads these tokens, so the theme lives here:
      //   primary   = Emerald (healing green, primary actions)   emerald-600 / hover emerald-700
      //   secondary = Saffron (alerts, tokens, triage highlights) orange-600 / orange-500
      //   tertiary  = Deep teal (supporting accent)               teal-700
      //   surfaces  = warm stone neutrals that sit well with saffron
      colors: {
        primary: '#059669',
        'on-primary': '#ffffff',
        'primary-container': '#047857',
        'on-primary-container': '#d1fae5',
        'primary-fixed': '#d1fae5',
        'primary-fixed-dim': '#6ee7b7',
        'on-primary-fixed': '#022c22',
        'on-primary-fixed-variant': '#065f46',
        'inverse-primary': '#6ee7b7',
        'surface-tint': '#059669',

        secondary: '#ea580c',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed7aa',
        'on-secondary-container': '#7c2d12',
        'secondary-fixed': '#ffedd5',
        'secondary-fixed-dim': '#fdba74',
        'on-secondary-fixed': '#431407',
        'on-secondary-fixed-variant': '#9a3412',

        tertiary: '#0f766e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5eead4',
        'on-tertiary-container': '#134e4a',
        'tertiary-fixed': '#ccfbf1',
        'tertiary-fixed-dim': '#5eead4',
        'on-tertiary-fixed': '#042f2e',
        'on-tertiary-fixed-variant': '#115e59',

        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        background: '#fffbf5',
        'on-background': '#1c1917',
        surface: '#fffbf5',
        'surface-bright': '#fffbf5',
        'surface-dim': '#e5d9c7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fdf6ec',
        'surface-container': '#f8efe2',
        'surface-container-high': '#f2e7d8',
        'surface-container-highest': '#ebdfcd',
        'surface-variant': '#ebdfcd',
        'on-surface': '#1c1917',
        'on-surface-variant': '#57534e',
        outline: '#78716c',
        'outline-variant': '#d6d3d1',
        'inverse-surface': '#292524',
        'inverse-on-surface': '#fafaf9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gutter-md': '1rem',
        'margin-desktop': '3.5rem',
        'gutter-xs': '0.25rem',
        'gutter-xl': '2rem',
        'gutter-2xl': '3rem',
        'margin-tablet': '2rem',
        'gutter-sm': '0.5rem',
        'margin-mobile': '1rem',
        'gutter-lg': '1.5rem',
      },
      fontFamily: {
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Source Serif 4', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Source Serif 4', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Source Serif 4', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Source Serif 4', 'serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-mobile': ['Source Serif 4', 'serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
