/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d6e6df',
        'primary-fixed-dim': '#aacfb7',
        'tertiary-container': '#4d755e',
        'surface-tint': '#446652',
        outline: '#727973',
        'inverse-surface': '#25332e',
        'on-tertiary-fixed-variant': '#274e3a',
        'on-surface-variant': '#424843',
        'secondary-fixed-dim': '#ffb597',
        'inverse-on-surface': '#e4f4ed',
        'primary-container': '#527460',
        'on-surface': '#111e1a',
        'on-background': '#111e1a',
        'tertiary-fixed-dim': '#a5d0b6',
        'on-primary-fixed': '#002112',
        primary: '#3a5b49',
        'surface-bright': '#edfdf5',
        error: '#ba1a1a',
        'on-tertiary-container': '#cdfadd',
        'outline-variant': '#c1c8c1',
        'secondary-container': '#fd9a6f',
        'surface-dim': '#ceded6',
        'secondary-fixed': '#ffdbcd',
        'surface-container-lowest': '#ffffff',
        surface: '#edfdf5',
        'surface-container': '#e2f2ea',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'primary-fixed': '#c6ebd3',
        'tertiary-fixed': '#c1edd1',
        'on-primary-container': '#d2f8df',
        'on-tertiary-fixed': '#002112',
        'on-secondary-container': '#76300d',
        'on-secondary-fixed-variant': '#77320e',
        'surface-container-low': '#e7f7f0',
        tertiary: '#355c47',
        'surface-container-high': '#dcece4',
        background: '#edfdf5',
        'surface-variant': '#d6e6df',
        secondary: '#964824',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#2c4d3b',
        'on-secondary-fixed': '#360f00',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'inverse-primary': '#aacfb7',
        'on-secondary-fixed': '#360f00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gutter-md': '1rem',
        'margin-desktop': '3.5rem',
        'gutter-xs': '0.25rem',
        'gutter-xl': '2rem',
        'gutter-2xl': '3rem',
        'margin-tablet': '2rem',
        'gutter-sm': '0.5rem',
        'margin-mobile': '1rem',
        'gutter-lg': '1.5rem',
      },
      fontFamily: {
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Source Serif 4', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Source Serif 4', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Source Serif 4', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Source Serif 4', 'serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-mobile': ['Source Serif 4', 'serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
