/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // Ayurvedic Clinical HealthOS palette (dark foundation). Every component reads these
      // tokens, so the whole platform's colour architecture lives here:
      //   surfaces  = warm espresso / sheesham stone — canvas #0f0d0b, cards stone-900
      //   primary   = healing forest sage / emerald (clinical commits, balanced states)
      //   secondary = burnished brass / saffron (clinical headers, markers, priority)
      //   tertiary  = muted sage (supporting accent)
      //   on-*      = parchment & ivory text (stone-100 / stone-400)
      // Surface steps get LIGHTER as they nest: canvas < lowest (cards) < low < … < highest.
      colors: {
        primary: '#059669',
        'on-primary': '#ffffff',
        'primary-container': '#047857',
        'on-primary-container': '#d1fae5',
        'primary-fixed': '#064e3b',
        'primary-fixed-dim': '#34d399',
        'on-primary-fixed': '#d1fae5',
        'on-primary-fixed-variant': '#6ee7b7',
        'inverse-primary': '#047857',
        'surface-tint': '#059669',

        secondary: '#f59e0b',
        'on-secondary': '#1c1917',
        'secondary-container': '#451a03',
        'on-secondary-container': '#fcd34d',
        'secondary-fixed': '#3b2208',
        'secondary-fixed-dim': '#d97706',
        'on-secondary-fixed': '#fef3c7',
        'on-secondary-fixed-variant': '#fcd34d',

        tertiary: '#8fb996',
        'on-tertiary': '#0f0d0b',
        'tertiary-container': '#1f3a2b',
        'on-tertiary-container': '#c7e3cc',
        'tertiary-fixed': '#1f3a2b',
        'tertiary-fixed-dim': '#8fb996',
        'on-tertiary-fixed': '#dcfce7',
        'on-tertiary-fixed-variant': '#bbf7d0',

        error: '#f87171',
        'on-error': '#1c1917',
        'error-container': '#4c0519',
        'on-error-container': '#fecdd3',

        background: '#0f0d0b',
        'on-background': '#f5f5f4',
        surface: '#0f0d0b',
        'surface-bright': '#292524',
        'surface-dim': '#0c0a09',
        'surface-container-lowest': '#1c1917',
        'surface-container-low': '#231f1c',
        'surface-container': '#292524',
        'surface-container-high': '#312c28',
        'surface-container-highest': '#44403c',
        'surface-variant': '#292524',
        'on-surface': '#f5f5f4',
        'on-surface-variant': '#a8a29e',
        outline: '#78716c',
        'outline-variant': '#44403c',
        'inverse-surface': '#e7e5e4',
        'inverse-on-surface': '#1c1917',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'gutter-md': '1rem',
        'margin-desktop': '3.5rem',
        'gutter-xs': '0.25rem',
        'gutter-xl': '2rem',
        'gutter-2xl': '3rem',
        'margin-tablet': '2rem',
        'gutter-sm': '0.5rem',
        'margin-mobile': '1rem',
        'gutter-lg': '1.5rem',
      },
      fontFamily: {
        // AYUSH terminology accents; numbers and lab values stay in the sans stack.
        serif: ['Source Serif 4', 'Georgia', 'serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile': ['Source Serif 4', 'serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Source Serif 4', 'serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Source Serif 4', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Source Serif 4', 'serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-mobile': ['Source Serif 4', 'serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '0em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
